### ISSUE TITLE
Eas build error

### ISSUE THREAD

**Issue by dcesca** [OneSignal/onesignal-expo-plugin#111]
Hi, I just updated the plugin and with eas gives me thi error:
ag for more details.
401
[stderr] error The resource
"/home/expo/workingdir/build/onesignal-expo-plugin: No specifiC actions required for OneSignAl on Android.
402
[stderr] index.js was not found.

I use expo 45, should I upgrade to 46?

**Comment by metadevj** [comment]
```
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" complete.
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.
Checking the license for package Android SDK Platform 31 in /home/expo/Android/Sdk/licenses
License for package Android SDK Platform 31 accepted.
Preparing "Install Android SDK Platform 31 (revision: 1)".
"Install Android SDK Platform 31 (revision: 1)" ready.
Installing Android SDK Platform 31 in /home/expo/Android/Sdk/platforms/android-31
"Install Android SDK Platform 31 (revision: 1)" complete.
"Install Android SDK Platform 31 (revision: 1)" finished.
Checking the license for package Android SDK Build-Tools 31 in /home/expo/Android/Sdk/licenses
License for package Android SDK Build-Tools 31 accepted.
Preparing "Install Android SDK Build-Tools 31 (revision: 31.0.0)".
"Install Android SDK Build-Tools 31 (revision: 31.0.0)" ready.
Installing Android SDK Build-Tools 31 in /home/expo/Android/Sdk/build-tools/31.0.0
"Install Android SDK Build-Tools 31 (revision: 31.0.0)" complete.
"Install Android SDK Build-Tools 31 (revision: 31.0.0)" finished.
The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':expo', ':expo-modules-core'
> Task :app:bundleReleaseJsAndAssets
    onesignal-expo-plugin: No specific actions required for OneSignal on Android...
warning: the transform cache was reset.
Error: The resource `/home/expo/workingdir/build/onesignal-expo-plugin: No specific actions required for OneSignal on Android...
index.js` was not found.
    at /home/expo/workingdir/build/node_modules/metro/src/IncrementalBundler.js:297:24
    at gotStat (node:fs:2637:21)
    at FSReqCallback.oncomplete (node:fs:198:21)
info Run CLI with --verbose flag for more details.
> Task :app:bundleReleaseJsAndAssets FAILED
[stderr] error The resource `/home/expo/workingdir/build/onesignal-expo-plugin: No specific actions required for OneSignal on Android...
[stderr] index.js` was not found.
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:bundleReleaseJsAndAssets'.
[stderr] > Process 'command 'node'' finished with non-zero exit value 1
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 2m 51s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
7 actionable tasks: 7 executed
Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" complete.
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.
Checking the license for package Android SDK Platform 31 in /home/expo/Android/Sdk/licenses
License for package Android SDK Platform 31 accepted.
Preparing "Install Android SDK Platform 31 (revision: 1)".
"Install Android SDK Platform 31 (revision: 1)" ready.
Installing Android SDK Platform 31 in /home/expo/Android/Sdk/platforms/android-31
"Install Android SDK Platform 31 (revision: 1)" complete.
"Install Android SDK Platform 31 (revision: 1)" finished.
Checking the license for package Android SDK Build-Tools 31 in /home/expo/Android/Sdk/licenses
License for package Android SDK Build-Tools 31 accepted.
Preparing "Install Android SDK Build-Tools 31 (revision: 31.0.0)".
"Install Android SDK Build-Tools 31 (revision: 31.0.0)" ready.
Installing Android SDK Build-Tools 31 in /home/expo/Android/Sdk/build-tools/31.0.0
"Install Android SDK Build-Tools 31 (revision: 31.0.0)" complete.
"Install Android SDK Build-Tools 31 (revision: 31.0.0)" finished.
The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':expo', ':expo-modules-core'
> Task :app:bundleReleaseJsAndAssets
    onesignal-expo-plugin: No specific actions required for OneSignal on Android...
warning: the transform cache was reset.
Error: The resource `/home/expo/workingdir/build/onesignal-expo-plugin: No specific actions required for OneSignal on Android...
index.js` was not found.
    at /home/expo/workingdir/build/node_modules/metro/src/IncrementalBundler.js:297:24
    at gotStat (node:fs:2637:21)
    at FSReqCallback.oncomplete (node:fs:198:21)
info Run CLI with --verbose flag for more details.
> Task :app:bundleReleaseJsAndAssets FAILED
[stderr] error The resource `/home/expo/workingdir/build/onesignal-expo-plugin: No specific actions required for OneSignal on Android...
[stderr] index.js` was not found.
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:bundleReleaseJsAndAssets'.
[stderr] > Process 'command 'node'' finished with non-zero exit value 1
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 2m 51s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
7 actionable tasks: 7 executed
Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

**Comment by epileftro85** [comment]
Same Error, i ran it in android studio too but got 
The resource onesignal-expo-plugin: No specific actions required for OneSignal on Android

**Comment by rgomezp** [comment]
Howdy y'all.
Thank you for reporting.

We removed the automatic installation of the onesignal Gradle plugin which we will no longer support moving forward. The latest release is a minor release for this reason. This is mostly due to the significant amelioration of Android versioning issues compared with years past.

@brismithers can you provide further details on available options?

In the meantime, please consider returning to the previous version as a workaround.

Thanks for your understanding.

**Comment by badinenisaivardhan** [comment]
Got Same Error .. Using onesignal-expo-plugin@latest , need to check with downgrading to previous version..! 
![image](https://user-images.githubusercontent.com/24708206/188487905-227a11cb-30d1-45a5-aa78-1192dcd1b58d.png)

**Comment by metadevj** [comment]
downgrading to 1.0.2 works

`"onesignal-expo-plugin": "1.0.2",`

**Comment by AashiqDurga** [comment]
I am getting the same error, using `onesignal-expo-plugin": "^1.0.2"`

**Comment by metadevj** [comment]
@AashiqDurga remove the "^" see https://www.freecodecamp.org/news/what-is-npm-a-node-package-manager-tutorial-for-beginners/

**Comment by badinenisaivardhan** [comment]
> downgrading to 1.0.2 works
> 
> `"onesignal-expo-plugin": "1.0.2",`

it is woking with 1.0.2, thanks @metadevj

**Comment by brismithers** [comment]
Apologies everyone, it looks like that additional `console.log` that was added is causing a problem with EAS builds only, I think it's related to this [issue](https://github.com/expo/eas-cli/issues/1226).  

I'll create a new release that removes the log message until we can verify the expo change addresses our issue.
