### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'smallIcons')

### ISSUE THREAD

**Issue by YahyaBagia** [OneSignal/onesignal-expo-plugin#150]
### What happened?

`npx expo prebuild`, `yarn ios` and `yarn android` commands are failing with the error message `TypeError: Cannot read properties of undefined (reading 'smallIcons')` after installing `onesignal-expo-plugin` and `react-native-onesignal`.

<img width="1169" alt="Screenshot 2022-12-10 at 11 41 29 PM" src="https://user-images.githubusercontent.com/25579208/206869418-bd6354d5-4074-4a28-aeb0-95d6012d49ec.png">

I have added two files named `ic_stat_onesignal_default.png` & `ic_onesignal_large_icon_default.png` in the `/assets` folder. `smallIcons` & `largeIcons` are also set in `app.json` -> `expo` -> `plugins` -> `onesignal-expo-plugin`.

<img width="696" alt="Screenshot 2022-12-10 at 11 35 05 PM" src="https://user-images.githubusercontent.com/25579208/206869284-5c01236d-8e19-4fcb-bc3e-9c0163e650a5.png">
<img width="407" alt="Screenshot 2022-12-10 at 11 35 22 PM" src="https://user-images.githubusercontent.com/25579208/206869286-5f053266-03aa-4504-b8ea-d06991657092.png">

### Steps to reproduce?

```Markdown
Dependencies:
"expo": "~47.0.8"
"react-native": "0.70.5"
"onesignal-expo-plugin": "^1.3.0"
"react-native-onesignal": "^4.5.0"

Failing Commands:
`npx expo prebuild`
`yarn ios`
`yarn android`
```

### What did you expect to happen?

Successfully generate `/ios` and `/android` (native project) directories. 

### OneSignal Expo SDK version

"onesignal-expo-plugin": "^1.3.0"
"react-native-onesignal": "^4.5.0"

### Platform

iOS, Android

### Relevant log output

```Shell
yahyabagia@Yahyas-MacBook-Air BISAppNew % npx expo prebuild

CommandError: Cannot read properties of undefined (reading 'smallIcons')

yahyabagia@Yahyas-MacBook-Air BISAppNew % yarn ios         
yarn run v1.22.19
$ expo start --ios
Starting project at /Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew
TypeError: Cannot read properties of undefined (reading 'smallIcons')
TypeError: Cannot read properties of undefined (reading 'smallIcons')
    at withSmallIcons (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignalAndroid.js:28:25)
    at withOneSignalAndroid (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignalAndroid.js:85:14)
    at withOneSignal (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignal.js:11:62)
    at withStaticPlugin (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js:157:12)
    at /Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:38:84
    at Array.reduce (<anonymous>)
    at withPlugins (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:38:18)
    at withConfigPlugins (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config/build/plugins/withConfigPlugins.js:45:47)
    at fillAndReturnConfig (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config/build/Config.js:315:78)
    at getConfig (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config/build/Config.js:382:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yahyabagia@Yahyas-MacBook-Air BISAppNew % yarn android
yarn run v1.22.19
$ expo start --android
Starting project at /Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew
TypeError: Cannot read properties of undefined (reading 'smallIcons')
TypeError: Cannot read properties of undefined (reading 'smallIcons')
    at withSmallIcons (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignalAndroid.js:28:25)
    at withOneSignalAndroid (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignalAndroid.js:85:14)
    at withOneSignal (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignal.js:11:62)
    at withStaticPlugin (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js:157:12)
    at /Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:38:84
    at Array.reduce (<anonymous>)
    at withPlugins (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:38:18)
    at withConfigPlugins (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config/build/plugins/withConfigPlugins.js:45:47)
    at fillAndReturnConfig (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config/build/Config.js:315:78)
    at getConfig (/Users/yahyabagia/Desktop/Projects/Work/BIS/BISAppNew/node_modules/@expo/config/build/Config.js:382:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @YahyaBagia, it looks like it's choking on this [line](https://github.com/OneSignal/onesignal-expo-plugin/blob/main/onesignal/withOneSignalAndroid.ts#L34) and it's indicating `onesignalProps` is null, which I would not expect.

I'm wondering if it's an environmental issue, can you tell me what version of `node`, `npx` and `yarn` you are using?

**Comment by YahyaBagia** [comment]
@brismithers 
Thank you for your prompt reply.

Here you go.
node : v18.12.1
npm : 8.19.2
yarn : 1.22.19
npx : 8.19.2

**Comment by brismithers** [comment]
Thanks for the info @ShebaAnnaPhilip and @YahyaBagia.  Turns out it isn't an environmental issue, it looks like it's the config itself.  Your plugin configuration should be as follows (note the nested array, when providing configuration options to the plugin!):

```
    "plugins": [
      [
        "onesignal-expo-plugin",
        {
          "mode": "development",
          "devTeam": "YOURDEVTEAM",
          "smallIcons": ["./assets/ic_state_onesignal_default.png"],
          "largeIcons": ["./assets/ic_onesignal_large_icon_default.png"]
        }
      ]
    ],
```

See [here](https://docs.expo.dev/guides/config-plugins/#using-a-plugin-in-your-app) for more information on the syntax.  Hope this helps!

**Comment by YahyaBagia** [comment]
Thank you @brismithers for catching the issue.

**Comment by Jerry2001Qu** [comment]
Ah! I've been stuck on this for so long. Thank you for figuring it out!
