### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'smallIcons')

### ISSUE THREAD

**Issue by tomwisecodes** [OneSignal/onesignal-expo-plugin#191]
### What happened?

On install I get this error. If I try and carry on past it it causes the prebuild to fail here also.

### Steps to reproduce?

```Markdown
npx expo install onesignal-expo-plugin
```

### What did you expect to happen?

Expected to be able to install one signal

### OneSignal Expo SDK version

"expo": "~49.0.3",
"react-native-onesignal": "^4.5.1",
"onesignal-expo-plugin": "^1.3.2"

### Platform

iOS

### Relevant log output

```Shell
at withSmallIcons (/Users/tomoak/Documents/GitHub/digin-app/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignalAndroid.js:28:25)
    at withOneSignalAndroid (/Users/tomoak/Documents/GitHub/digin-app/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignalAndroid.js:85:14)
    at withOneSignal (/Users/tomoak/Documents/GitHub/digin-app/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignal.js:11:62)
    at withStaticPlugin (/Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js:136:12)
    at /Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:84
    at Array.reduce (<anonymous>)
    at withPlugins (/Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:18)
    at withConfigPlugins (/Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config/build/plugins/withConfigPlugins.js:36:47)
    at fillAndReturnConfig (/Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config/build/Config.js:217:78)
    at Object.getConfig (/Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config/build/Config.js:272:10)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomwisecodes** [comment]
TypeError: Cannot read properties of undefined (reading 'smallIcons')at withSmallIcons (/Users/tomoak/Documents/GitHub/digin-app/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignalAndroid.js:28:25)
    at withOneSignalAndroid (/Users/tomoak/Documents/GitHub/digin-app/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignalAndroid.js:85:14)
    at withOneSignal (/Users/tomoak/Documents/GitHub/digin-app/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignal.js:11:62)
    at withStaticPlugin (/Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js:136:12)
    at /Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:84
    at Array.reduce (<anonymous>)
    at withPlugins (/Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:18)
    at withConfigPlugins (/Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config/build/plugins/withConfigPlugins.js:36:47)
    at fillAndReturnConfig (/Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config/build/Config.js:217:78)
    at Object.getConfig (/Users/tomoak/Documents/GitHub/digin-app/node_modules/@expo/config/build/Config.js:272:10)

**Comment by mantagen** [comment]
@tomwisecodes it looks like you have your plugin config incorrectly set up in `app.json` (or equivalent).
It should read:
```json
  plugins: [
    // other plugins,
    ["onesignal-expo-plugin", {
      // onesignal config
    }]
  ]
```

You can find the  [as described here](https://github.com/OneSignal/onesignal-expo-plugin#plugin)
