### ISSUE TITLE
oneSignal small icon error in expo sdk ( Cannot read properties of undefined (reading 'smallIcons'))[feedback]

### ISSUE THREAD

**Issue by jasim00021** [OneSignal/onesignal-expo-plugin#192]
### Expo sdk error small icon not found

TypeError: Cannot read properties of undefined (reading 'smallIcons')
    at withSmallIcons (/home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignalAndroid.js:28:25)
    at withOneSignalAndroid (/home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignalAndroid.js:85:14)
    at withOneSignal (/home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/onesignal-expo-plugin/build/onesignal/withOneSignal.js:11:62)
    at withStaticPlugin (/home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js:136:12)
    at /home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:84
    at Array.reduce (<anonymous>)
    at withPlugins (/home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:18)
    at withConfigPlugins (/home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/@expo/config/build/plugins/withConfigPlugins.js:36:47)
    at fillAndReturnConfig (/home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/@expo/config/build/Config.js:217:78)
    at getConfig (/home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/@expo/config/build/Config.js:272:10)
    at startAsync (/home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/@expo/cli/build/src/start/startAsync.js:93:68)
    at expoStart (/home/techwens/Techwens_jasim_backup/jasim/new-outAbout/outabout-react/node_modules/@expo/cli/build/src/start/index.js:110:12)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jasim00021** [comment]
d

**Comment by rgomezp** [comment]
Please follow our issue template so we can better assist you.
