### ISSUE TITLE
[Bug]: iOS Error: Consistency issue: no parent for object `NotificationService.m`

### ISSUE THREAD

**Issue by vinz-mehra** [OneSignal/onesignal-expo-plugin#239]
### What happened?

Using version 2.0.3 when I try to use Pod Install. I get the error 

`[Xcodeproj] Consistency issue: no parent for object `NotificationService.m`: `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase``

package.json

`{
  "name": "app",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "eslint ."
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@nozbe/watermelondb": "^0.27.1",
    "@react-native-firebase/analytics": "^20.4.0",
    "@react-native-firebase/app": "^20.4.0",
    "@react-navigation/native": "^6.0.2",
    "@tanstack/react-query": "^5.51.1",
    "expo": "~51.0.28",
    "expo-font": "~12.0.9",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.23",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-web-browser": "~13.0.3",
    "onesignal-expo-plugin": "^2.0.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5",
    "react-native-admob-native-ads": "^0.7.6",
    "react-native-date-picker": "^5.0.4",
    "react-native-device-info": "^11.1.0",
    "react-native-fbsdk-next": "^13.0.0",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-in-app-review": "^4.3.3",
    "react-native-mmkv": "^2.11.2",
    "react-native-onesignal": "^5.2.4",
    "react-native-reanimated": "~3.10.1",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-share": "^11.0.2",
    "react-native-size-matters": "^0.4.2",
    "react-native-view-shot": "3.8.0",
    "react-native-web": "~0.19.10",
    "zustand": "^4.5.4",
    "expo-build-properties": "~0.12.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "eslint": "^8.57.0",
    "eslint-config-expo": "^7.1.2",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.2.1",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.3",
    "prettier": "^3.3.3",
    "react-test-renderer": "18.2.0",
    "typescript": "~5.3.3"
  },
  "private": true
}
`

app.json

`
{
  "expo": {
    "name": "app",
    "slug": "app",
    "version": "1.0.1",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "backgroundColor": "#0D0D0D",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#0D0D0D"
    },
    "ios": {
      "supportsTablet": true,
      "googleServicesFile": "./GoogleService-Info.plist",
      "bundleIdentifier": "com.app.app"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#132e79"
      },
      "googleServicesFile": "./google-services.json",
      "package":  "com.app.app"
      "versionCode": 16
    },
    "web": {
      "bundler": "metro",
      "output": "static",
      "favicon": "./assets/images/favicon.png"
    },
    "plugins": [
      [
        "onesignal-expo-plugin",
        {
          "mode": "development",
          "iPhoneDeploymentTarget": "12.0",
          "smallIcons": [
            "./assets/images/ic_stat_onesignal_default.png"
          ],
          "largeIcons": [
            "./assets/images/ic_onesignal_large_icon_default.png"
          ]
        }
      ],
      "expo-router",
      "@react-native-firebase/app",
      [
        "react-native-admob-native-ads",
        {
          "androidAppId": "ca-app-pub-~",
          "iosAppId": "ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy",
          "facebookMediation": false
        }
      ],
    
      [
        "react-native-fbsdk-next",
        {
          "appID": "",
          "clientToken": "",
          "displayName": "",
          "scheme": "",
          "autoLogAppEventsEnabled": true,
          "isAutoInitEnabled": true
        }
      ],
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ],
    "experiments": {
      "typedRoutes": true
    },
    "extra": {
      "router": {
        "origin": false
      },
      "eas": {
        "projectId": ""
      }
    }
  }
}
`

### Steps to reproduce?

```Markdown
Having build error
```

### What did you expect to happen?

Expected pod install to work but instead got the error.

### OneSignal Expo SDK version

2.0.3

### Relevant log output

```Shell
No modules to process in combine-js-to-schema-cli. If this is unexpected, please check if you set up your NativeComponent correctly. See combine-js-to-schema.js for how codegen finds modules.
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `fmt` from `../node_modules/react-native/third-party-podspecs/fmt.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.74.5/react-native-artifacts-0.74.5-hermes-ios-debug.tar.gz
/Users/vinz/Documents/projects/citcurrentaffairs/node_modules/react-native-fbsdk-next/react-native-fbsdk-next.podspec:4: warning: already initialized constant Pod::FBSDKVersion
/Users/vinz/Documents/projects/citcurrentaffairs/node_modules/react-native-fbsdk-next/react-native-fbsdk-next.podspec:4: warning: previous definition of FBSDKVersion was here
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing EXConstants (16.0.2)
Installing EXSplashScreen (0.27.5)
Installing Expo (51.0.32)
Installing ExpoAdapterFBSDKNext (13.0.0)
Installing ExpoAsset (10.0.10)
Installing ExpoFileSystem (17.0.1)
Installing ExpoFont (12.0.10)
Installing ExpoHead (3.5.23)
Installing ExpoKeepAwake (13.0.2)
Installing ExpoModulesCore (1.12.24)
Installing ExpoSystemUI (3.0.7)
Installing ExpoWebBrowser (13.0.3)
Installing FBAEMKit (17.0.3)
Installing FBLazyVector (0.74.5)
Installing FBSDKCoreKit (17.0.3)
Installing FBSDKCoreKit_Basics (17.0.3)
Installing FBSDKGamingServicesKit (17.0.3)
Installing FBSDKLoginKit (17.0.3)
Installing FBSDKShareKit (17.0.3)
Installing Firebase (10.29.0)
Installing FirebaseAnalytics (10.29.0)
Installing FirebaseCore (10.29.0)
Installing FirebaseCoreInternal (10.29.0)
Installing FirebaseInstallations (10.29.0)
Installing Google-Mobile-Ads-SDK (11.12.0)
Installing GoogleAppMeasurement (10.29.0)
Installing GoogleUserMessagingPlatform (2.7.0)
Installing GoogleUtilities (7.13.3)
Installing MMKV (2.0.0)
Installing MMKVCore (2.0.0)
Installing OneSignalXCFramework (5.2.4)
Installing PromisesObjC (2.4.0)
Installing RCT-Folly (2024.01.01.00)
Installing RCTDeprecation (0.74.5)
Installing RCTRequired (0.74.5)
Installing RCTTypeSafety (0.74.5)
Installing RNDeviceInfo (11.1.0)
Installing RNFBAnalytics (20.4.0)
Installing RNFBApp (20.4.0)
Installing RNGestureHandler (2.16.2)
Installing RNReanimated (3.10.1)
Installing RNScreens (3.31.1)
Installing RNShare (11.0.2)
Installing React (0.74.5)
Installing React-Codegen (0.74.5)
Installing React-Core (0.74.5)
Installing React-CoreModules (0.74.5)
Installing React-Fabric (0.74.5)
Installing React-FabricImage (0.74.5)
Installing React-ImageManager (0.74.5)
Installing React-Mapbuffer (0.74.5)
Installing React-NativeModulesApple (0.74.5)
Installing React-RCTActionSheet (0.74.5)
Installing React-RCTAnimation (0.74.5)
Installing React-RCTAppDelegate (0.74.5)
Installing React-RCTBlob (0.74.5)
Installing React-RCTFabric (0.74.5)
Installing React-RCTImage (0.74.5)
Installing React-RCTLinking (0.74.5)
Installing React-RCTNetwork (0.74.5)
Installing React-RCTSettings (0.74.5)
Installing React-RCTText (0.74.5)
Installing React-RCTVibration (0.74.5)
Installing React-RuntimeApple (0.74.5)
Installing React-RuntimeCore (0.74.5)
Installing React-RuntimeHermes (0.74.5)
Installing React-callinvoker (0.74.5)
Installing React-cxxreact (0.74.5)
Installing React-debug (0.74.5)
Installing React-featureflags (0.74.5)
Installing React-graphics (0.74.5)
Installing React-hermes (0.74.5)
Installing React-jserrorhandler (0.74.5)
Installing React-jsi (0.74.5)
Installing React-jsiexecutor (0.74.5)
Installing React-jsinspector (0.74.5)
Installing React-jsitracing (0.74.5)
Installing React-logger (0.74.5)
Installing React-nativeconfig (0.74.5)
Installing React-perflogger (0.74.5)
Installing React-rendererdebug (0.74.5)
Installing React-rncore (0.74.5)
Installing React-runtimeexecutor (0.74.5)
Installing React-runtimescheduler (0.74.5)
Installing React-utils (0.74.5)
Installing ReactCommon (0.74.5)
Installing SocketRocket (0.7.0)
Installing WatermelonDB (0.27.1)
Installing Yoga (0.0.0)
Installing boost (1.83.0)
Installing fmt (9.1.0)
Installing glog (0.3.5)
Installing hermes-engine (0.74.5)
Installing nanopb (2.30910.0)
Installing react-native-admob-native-ads (0.7.6)
Installing react-native-date-picker (5.0.7)
Installing react-native-fbsdk-next (13.0.0)
Installing react-native-in-app-review (4.3.3)
Installing react-native-mmkv (2.12.2)
Installing react-native-onesignal (5.2.4)
Installing react-native-render-html (6.3.4)
Installing react-native-safe-area-context (4.10.5)
Installing react-native-view-shot (3.8.0)
Installing simdjson (3.1.0-wmelon1)
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

[Xcodeproj] Consistency issue: no parent for object `NotificationService.m`: `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`

/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object/helpers/groupable_helper.rb:19:in `parent'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object/build_file.rb:77:in `ascii_plist_annotation'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:297:in `block in to_ascii_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:296:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:296:in `to_ascii_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:365:in `block in save'
/Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:364:in `save'
/Users/vinz/Documents/projects/citcurrentaffairs/node_modules/react-native/scripts/cocoapods/utils.rb:153:in `block in fix_library_search_paths'
/Users/vinz/Documents/projects/citcurrentaffairs/node_modules/react-native/scripts/cocoapods/utils.rb:144:in `each'
/Users/vinz/Documents/projects/citcurrentaffairs/node_modules/react-native/scripts/cocoapods/utils.rb:144:in `fix_library_search_paths'
/Users/vinz/Documents/projects/citcurrentaffairs/node_modules/react-native/scripts/react_native_pods.rb:294:in `react_native_post_install'
/Users/vinz/Documents/projects/citcurrentaffairs/ios/Podfile:65:in `block (3 levels) in from_ruby'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:183:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:170:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

[!] [Codegen] warn: using experimental new codegen integration

[!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `098DB41F49B74E748FB60293` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ilyaLibin** [comment]
Did you manage to solve it? I have a same issue @vinz-mehra

**Comment by rares-lupascu** [comment]
same here

**Comment by wickeym** [comment]
Same issue.

**Comment by mtflud** [comment]
After spending an excessive amount of time troubleshooting, I discovered that the issue stemmed from applying the `onesignal-expo-plugin` multiple times—specifically, once in my `app.json` and again in my dynamic `app.config.ts`. If you're encountering similar build errors or duplicate configuration issues, make sure the plugin is only applied once in your project configuration.

**Comment by eLandFly-AMARIN** [comment]
Same error, I only have one specification:

`Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

[Xcodeproj] Consistency issue: no parent for object `NotificationService.m`: `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`

/usr/local/lib/ruby/gems/3.4.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object/helpers/groupable_helper.rb:19:in 'Xcodeproj::Project::Object::GroupableHelper.parent'
/usr/local/lib/ruby/gems/3.4.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object/build_file.rb:77:in 'Xcodeproj::Project::Object::PBXBuildFile#ascii_plist_annotation'
/usr/local/lib/ruby/gems/3.4.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:297:in 'block in Xcodeproj::Project#to_ascii_plist'
/usr/local/lib/ruby/gems/3.4.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:296:in 'Array#each'
/usr/local/lib/ruby/gems/3.4.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:296:in 'Xcodeproj::Project#to_ascii_plist'
/usr/local/lib/ruby/gems/3.4.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:365:in 'block in Xcodeproj::Project#save'
/usr/local/lib/ruby/gems/3.4.0/gems/atomos-0.1.3/lib/atomos.rb:21:in 'block in Atomos.atomic_write'
/usr/local/Cellar/ruby/3.4.1/lib/ruby/3.4.0/tempfile.rb:444:in 'Tempfile.open'
/usr/local/lib/ruby/gems/3.4.0/gems/atomos-0.1.3/lib/atomos.rb:17:in 'Atomos.atomic_write'
/usr/local/lib/ruby/gems/3.4.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:364:in 'Xcodeproj::Project#save'
/Users/alvaro.marin/DESARROLLO/REACT/ficharapp/FicharApp/node_modules/react-native/scripts/cocoapods/utils.rb:150:in 'block in ReactNativePodsUtils.fix_library_search_paths'
/Users/alvaro.marin/DESARROLLO/REACT/ficharapp/FicharApp/node_modules/react-native/scripts/cocoapods/utils.rb:141:in 'Array#each'
/Users/alvaro.marin/DESARROLLO/REACT/ficharapp/FicharApp/node_modules/react-native/scripts/cocoapods/utils.rb:141:in 'ReactNativePodsUtils.fix_library_search_paths'
/Users/alvaro.marin/DESARROLLO/REACT/ficharapp/FicharApp/node_modules/react-native/scripts/react_native_pods.rb:430:in 'Object#react_native_post_install'
/Users/alvaro.marin/DESARROLLO/REACT/ficharapp/FicharApp/ios/Podfile:53:in 'block (3 levels) in Pod::Podfile.from_ruby'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-core-1.16.2/lib/cocoapods-core/podfile.rb:196:in 'Pod::Podfile#post_install!'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1013:in 'Pod::Installer#run_podfile_post_install_hook'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1001:in 'block in Pod::Installer#run_podfile_post_install_hooks'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:149:in 'Pod::UserInterface.message'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1000:in 'Pod::Installer#run_podfile_post_install_hooks'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:337:in 'block (2 levels) in Pod::Installer#create_and_save_projects'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in 'Pod::Installer::Xcode::PodsProjectWriter#write!'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:336:in 'block in Pod::Installer#create_and_save_projects'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in 'Pod::UserInterface.section'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:315:in 'Pod::Installer#create_and_save_projects'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:307:in 'Pod::Installer#generate_pods_project'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:183:in 'Pod::Installer#integrate'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:170:in 'Pod::Installer#install!'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/command/install.rb:52:in 'Pod::Command::Install#run'
/usr/local/lib/ruby/gems/3.4.0/gems/claide-1.1.0/lib/claide/command.rb:334:in 'CLAide::Command.run'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in 'Pod::Command.run'
/usr/local/lib/ruby/gems/3.4.0/gems/cocoapods-1.16.2/bin/pod:55:in '<top (required)>'
/usr/local/Cellar/cocoapods/1.16.2_1/libexec/bin/pod:25:in 'Kernel#load'
/usr/local/Cellar/cocoapods/1.16.2_1/libexec/bin/pod:25:in '<main>'`

**Comment by VirtualDOMinic** [comment]
> After spending an excessive amount of time troubleshooting, I discovered that the issue stemmed from applying the `onesignal-expo-plugin` multiple times—specifically, once in my `app.json` and again in my dynamic `app.config.ts`. If you're encountering similar build errors or duplicate configuration issues, make sure the plugin is only applied once in your project configuration.

@mtflud I came across this issue this week and can't imagine how long it might have taken me to discover this solution! Thanks for following up! Now I just need to fix the subsequent errors that came up 😆

**Comment by fadi-george** [comment]
I'll close for now, check if onesignal-expo-plugin is used multiple times.
